# Generated by Django 3.0.5 on 2021-06-24 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_paper_student_data_teacher_edu_teachers_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teachers_data',
            old_name='github',
            new_name='researchgate',
        ),
        migrations.RenameField(
            model_name='teachers_data',
            old_name='linkedin',
            new_name='scholar',
        ),
    ]
