# Generated by Django 3.0.5 on 2021-06-24 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20210624_1655'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teachers_data',
            old_name='researchgate',
            new_name='sust_id',
        ),
    ]
