# Generated by Django 3.0.5 on 2021-06-25 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_form'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='student_1_majorcg',
            field=models.FloatField(blank=True, default=None, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='form',
            name='student_1_totalcg',
            field=models.FloatField(blank=True, default=None, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='form',
            name='student_2_majorcg',
            field=models.FloatField(blank=True, default=None, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='form',
            name='student_2_totalcg',
            field=models.FloatField(blank=True, default=None, max_length=5, null=True),
        ),
    ]
