# Generated by Django 3.0.5 on 2021-06-25 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_auto_20210625_2357'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='ssupervisor_1_name',
            field=models.CharField(blank=True, default=None, max_length=55, null=True),
        ),
        migrations.AddField(
            model_name='form',
            name='student_1_name',
            field=models.CharField(blank=True, default=None, max_length=55, null=True),
        ),
        migrations.AddField(
            model_name='form',
            name='student_2_name',
            field=models.CharField(blank=True, default=None, max_length=55, null=True),
        ),
        migrations.AddField(
            model_name='form',
            name='supervisor_2_name',
            field=models.CharField(blank=True, default=None, max_length=55, null=True),
        ),
        migrations.AddField(
            model_name='form',
            name='supervisor_3_name',
            field=models.CharField(blank=True, default=None, max_length=55, null=True),
        ),
        migrations.AddField(
            model_name='form',
            name='supervisor_4_name',
            field=models.CharField(blank=True, default=None, max_length=55, null=True),
        ),
        migrations.AddField(
            model_name='form',
            name='supervisor_5_name',
            field=models.CharField(blank=True, default=None, max_length=55, null=True),
        ),
    ]
