# Generated by Django 3.0.5 on 2021-06-25 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_auto_20210626_0145'),
    ]

    operations = [
        migrations.RenameField(
            model_name='form',
            old_name='ssupervisor_1_name',
            new_name='supervisor_1_name',
        ),
    ]
