# Generated by Django 3.0.5 on 2021-06-26 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_form_assigned_supervisor_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='action',
            field=models.CharField(blank=True, default='Save', max_length=55, null=True),
        ),
    ]
