# Generated by Django 3.0.5 on 2021-07-20 18:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_compact_form'),
    ]

    operations = [
        migrations.AddField(
            model_name='compact_form',
            name='student_1_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='compact_form',
            name='student_1_username',
            field=models.CharField(blank=True, default=None, max_length=55, null=True),
        ),
    ]
