# Generated by Django 3.0.5 on 2021-07-20 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_auto_20210721_0009'),
    ]

    operations = [
        migrations.AddField(
            model_name='compact_form',
            name='student_2_id',
            field=models.CharField(blank=True, default=None, max_length=55, null=True),
        ),
    ]
