# Generated by Django 3.0.5 on 2021-07-20 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_compact_form_student_2_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachers_data',
            name='photos',
            field=models.FileField(blank=True, default='teacher/uni1_.jpg', null=True, upload_to='teacher/'),
        ),
        migrations.DeleteModel(
            name='Form',
        ),
    ]
