# Generated by Django 3.0.5 on 2021-07-21 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_auto_20210721_0347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_data',
            name='photos',
            field=models.FileField(blank=True, default='https://sportlinx360.com/sites/default/files/public_uploads/Website_content/Website_Logos/graduate-student-avatar.png', null=True, upload_to='images/'),
        ),
    ]
