# Generated by Django 3.0.5 on 2021-07-21 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_auto_20210721_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_data',
            name='photos',
            field=models.FileField(blank=True, default='images/uni1_.jpg', null=True, upload_to='images/'),
        ),
    ]
