# Generated by Django 3.0.5 on 2021-07-24 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_auto_20210721_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_data',
            name='photos',
            field=models.FileField(blank=True, default='images/default.png', null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='teachers_data',
            name='photos',
            field=models.FileField(blank=True, default='teacher/default.png', null=True, upload_to='teacher/'),
        ),
    ]
