# Generated by Django 2.2 on 2021-07-30 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_notice'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachers_data',
            name='assigned_teams',
            field=models.IntegerField(blank=True, default=0, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='notice',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
