# Generated by Django 2.2 on 2021-07-30 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_auto_20210730_2244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachers_data',
            name='assigned_teams',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
